import Head from 'next/head'
import siteMetadata from '@/data/siteMetadata'
import { format, parseISO } from 'date-fns'
import { MDXLayoutRenderer } from '@/components/MDXComponents'
import { getPostsSlug } from '../../../lib/postData'
import { getFileBySlug } from '@/lib/mdx'


export default function BlogPage({ title, date, content, post}) {
  const { mdxSource, toc, frontMatter } = post
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <MDXLayoutRenderer
          layout={'PostSimple' || DEFAULT_LAYOUT}
          toc={toc}
          mdxSource={mdxSource}
          frontMatter={frontMatter}
        />
      </main>
    </div>
  )
}

export async function getStaticProps(context) {
    const { params } = context;
    const post = await getFileBySlug(params.slug)
    return {
      props: {
          post,
      }
    }
}

export async function getStaticPaths() {
  return {
      paths: getPostsSlug().map((post) => ({
          params: {
              slug: post.slug,
          },
      })),
      fallback: false,
  }
}

