import Head from 'next/head'
import { format, parseISO } from 'date-fns'
import { getAllPosts } from '../../lib/postData'
import { serialize } from 'next-mdx-remote/serialize'
import { MDXRemote } from 'next-mdx-remote'

export default function BlogPage({ title, date, content}) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="prose">
        <div className="border-b-2 border-gray-200">
          <h2 className="text-2xl font-bold">
            {title}
          </h2>
          <div className="text-gray-600 text-xd">
            {format(parseISO(date), 'MMM do, uuu')}
          </div>
        </div>
        <MDXRemote {...content} />
        {/* <div className="whitespace-pre">{...content}</div> */}
      </main>
    </div>
  )
}

export async function getStaticProps(context) {
    const { params } = context;
    const allPosts = getAllPosts();
    const { data, content} = allPosts.find((item) => item.slug === params.slug);
    const mdxSource = await serialize(content)
    return {
        props: {
            title: data.title,
            date: data.date.toISOString(),
            content: mdxSource,
        }
    }
}

export async function getStaticPaths() {
  return {
      paths: getAllPosts().map((post) => ({
          params: {
              slug: post.slug,
          },
      })),
      fallback: false,
  }
}

