import Head from 'next/head'
import siteMetadata from '@/data/siteMetadata'
import { format, parseISO } from 'date-fns'
import { getAllPosts } from '../../lib/postData'
import { MDXLayoutRenderer } from '@/components/MDXComponents'
// import { serialize } from 'next-mdx-remote/serialize'
// import { MDXRemote } from 'next-mdx-remote'
import { getFileBySlug } from '@/lib/mdx'


export default function BlogPage({ title, date, content, post}) {
  const { mdxSource, toc, frontMatter } = post
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        {/* <MDXRemote {...content} /> */}
        {/* <div className="whitespace-pre">{...content}</div> */}
        <MDXLayoutRenderer
          layout={'PostSimple' || DEFAULT_LAYOUT}
          toc={toc}
          mdxSource={mdxSource}
          frontMatter={frontMatter}
        />
      </main>
    </div>
  )
}

export async function getStaticProps(context) {
    const { params } = context;
    const allPosts = getAllPosts();
    const { data, content} = allPosts.find((item) => item.slug === params.slug);
    const post = await getFileBySlug('blog', params.slug)
    return {
      props: {
          title: data.title,
          date: data.date.toISOString(),
          content,
          post,
      }
    }
}

export async function getStaticPaths() {
  return {
      paths: getAllPosts().map((post) => ({
          params: {
              slug: post.slug,
          },
      })),
      fallback: false,
  }
}

