import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>About me</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <h1>
          Hi About me
        </h1>
      </main>
    </div>
  )
}
