import Head from 'next/head'
import { getAllPosts } from '../lib/postData'
import { format, parseISO } from 'date-fns'
import Link from 'next/link'
// import { getAllFilesFrontMatter } from '../lib/mdx'

// export async function getStaticProps() {
//   const posts = await getAllFilesFrontMatter('_content')

//   return { props: { posts } }
// }

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>MY BLOG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="space-y-4">
        {posts.map((post) => (
          <Link href={`/blog/${post.slug}`} key={post.slug}>
            <div>
              <BlogListItem key={post.slug} {...post} />
            </div>
          </Link>
        ))}
      </div>
    </div>
  )
}

export async function getStaticProps(context) {
  // const { params } = context;
  const allPosts = getAllPosts();
  console.log('allPosts', allPosts);

  // const { data, content} = allPosts.find((item) => item.slug === params.slug);
  // return {
  //     props: {
  //         title: data.title,
  //         date: data.date.toISOString(),
  //         content,
  //     }
  // }
  return { props: {
    posts: allPosts.map(({ data, content, slug}) => ({
      ...data,
      date: data.date.toISOString(),
      content,
      slug,
    }))
  } }
}

function BlogListItem({ slug, title, date, content}) {
 return (
  <div className="border border-pink-200 shadow rounded p-4 hover:cursor-pointer hover:shadow-md">
    <a className="text-lg font-bold">{title}</a>
    <div className="text-gray-600 text-xs">
      {format(parseISO(date), 'MMM do, uuu')}
    </div>
    <div>{content}</div>
  </div>
 )
}
